### ISSUE TITLE
tim_parse doesn't generate a plot.

### ISSUE THREAD

**Issue by Ilias9807** [pra-dan/TAMPPA#1]
-Using line_profiler 3.1.0
-Using TAMPPA 0.0.1
-On raspbian linux

Running a `tim_parse` command in terminal, on a .txt file which is the result of running a line profiling with `line_profiler`, does actually generate the 'again_func_names.txt' and 'func_name_tim_.csv' files, but it doesn't generate the plot that the documentation says it should (no error is raised).

Although running a `mem_parse` command on the same .txt file actually works as intended and both the appropriate files and the plot are generated. 

Of course having the .csv output from the `tim_parse` command, I can plot it myself with matplotlib and your package would still have saved me time, but it is weird that everything else works as intended BUT the time plotting.

Really usefull package though regardless.

**Comment by pra-dan** [comment]
Hello @Ilias9807 Thanks for checking out the package ✌️

From a quick glance, I realised that this may be due to the commented out part here

https://github.com/pra-dan/TAMPPA/blob/f5fc3006f013782aaf89105b417002e34e3fd007/tamppa/tamppa_code_tim.py#L105)

I will fix this bug and and try separating the plotting from parsing. But for a quick solution, I would advise you to clone the repo and then run the package as a non-pip package. Or simply, use the code from the source code, make your own python file and plot using matplotlib (the complete code for plotting can be found in the same file mentioned above). 

I hope it saves your time.

**Comment by pra-dan** [comment]
Do let me know if it solves your problem
